language: python
python:
- '3.8'
install:
- pip install -r requirements-travis.txt
script:
- python manage.py makemigrations
- python manage.py migrate
- python manage.py test
deploy:
  provider: heroku
  api_key:
    secure: Vc0wMygUZM5IemE0jrOayi6j+Q4oLJECtB1ySQUXZt/MiAd8TORVUUkUUN/AbjHVFLc0z6jqxUCjamPsByjsqiE4EuAkn7Vi4P7ayrzWaigdrobecq3cpFflI1ZftcJh4YwDLgRgN54jcnzgkVmjRzkhGo1YeI9PhqW1YQl4M0t+uSVQIh59Y9x0rdYID0tplphJMkSgElh1Ldo+jimDlfIv0FDsZKyR7pULwy96eEve2LIwHU1nOwrrcBM1j/jF8z6G3MxmnfXqxWyGLEg0Rkmssfc/GGpx6CXVoj3zkip3UrgY3PknLHOz+6WW0j5x2tA69oTYwiQk3Bcc2eiTGe7dgyl7niuPmDD7/7NGNo8z6iKV5KQi9jEAZ3RyQijVFienzSl7tmYiH5y3TSm4JmdrEreMhAuPPuog7P97a7meSAer12Y8sCQTQ0aifDM/zDlctyt4liCDWTpOp29oWvMsK2B8h4Qp7VVatXwNVt6w6/4xp3+EZF0CSd39Nb24gI84J3ylk+Nk22k7DyDWL5VXbUHEVg6FQmWFNw7TOf0x5nMXk99Vq8hUZ96HkNN679yncLEOpcBumwadrOvCZ32EuLdTJ5IV38Eu795BanjVe38DsF4V12n8/rZs/XSQAr9b57jl0W7Pw4mgu/n9PXyjlf8S2Vz6DMMovgoj1PQ=
  app: project-a-07
  on:
    branch: main
    repo: uva-cs3240-s21/project-a-07
