# Generated by Django 3.1.7 on 2021-03-21 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout_app', '0003_auto_20210321_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='duration',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='workout',
            name='intensity',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='workout',
            name='miles',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='workout',
            name='steps',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='workout',
            name='type',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
