# Generated by Django 3.1.7 on 2021-03-23 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout_app', '0008_auto_20210321_1602'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(default='', max_length=30)),
                ('has_intensity', models.BooleanField(default=False)),
                ('has_dist_comp', models.BooleanField(default=False)),
                ('has_raw_count_comp', models.BooleanField(default=False)),
                ('raw_count_comp_name', models.CharField(blank=True, default='', max_length=30)),
                ('has_set_rep_comp', models.BooleanField(default=False)),
                ('has_weight_comp', models.BooleanField(default=False)),
            ],
        ),
    ]
