# Generated by Django 3.1.7 on 2021-03-23 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout_app', '0009_workouttype'),
    ]

    operations = [
        migrations.AddField(
            model_name='workouttype',
            name='is_official_type',
            field=models.BooleanField(default=False),
        ),
    ]
