# Generated by Django 3.1.7 on 2021-03-24 01:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workout_app', '0012_workoutlinked'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutlinked',
            name='intensity',
            field=models.CharField(choices=[('L', 'Light'), ('M', 'Moderate'), ('V', 'Vigorous'), ('NA', 'Not Applicable')], default='L', max_length=2),
        ),
        migrations.AddField(
            model_name='workoutlinked',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workoutlinked',
            name='raw_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='workoutlinked',
            name='raw_rep',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='workoutlinked',
            name='raw_set',
            field=models.IntegerField(default=0),
        ),
    ]
