# Generated by Django 3.1.7 on 2021-03-24 01:13

from django.db import migrations
import django_measurement.models
import measurement.measures.distance


class Migration(migrations.Migration):

    dependencies = [
        ('workout_app', '0013_auto_20210323_2111'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutlinked',
            name='weight',
            field=django_measurement.models.MeasurementField(default=0, measurement=measurement.measures.distance.Distance),
        ),
    ]
