# Generated by Django 3.1.7 on 2021-03-24 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workout_app', '0016_auto_20210323_2123'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutTypeCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(default='', max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='workouttype',
            name='raw_count_comp_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workout_app.workouttypecount'),
        ),
    ]
