# Generated by Django 3.1.7 on 2021-03-24 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout_app', '0017_auto_20210323_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workouttype',
            name='raw_count_comp_name',
            field=models.CharField(default='', max_length=30),
        ),
    ]
