# Generated by Django 3.1.7 on 2021-03-24 02:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workout_app', '0018_auto_20210323_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workouttype',
            name='raw_count_comp_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workout_app.workouttypecount'),
        ),
    ]
