# Generated by Django 3.1.7 on 2021-03-24 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workout_app', '0019_auto_20210323_2217'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workouttype',
            old_name='raw_count_comp_name',
            new_name='count_component2',
        ),
        migrations.RenameField(
            model_name='workouttype',
            old_name='has_dist_comp',
            new_name='has_count_component',
        ),
        migrations.RenameField(
            model_name='workouttype',
            old_name='has_raw_count_comp',
            new_name='has_distance_comp',
        ),
    ]
