# Generated by Django 3.1.7 on 2021-03-24 02:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workout_app', '0020_auto_20210323_2223'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workouttype',
            old_name='has_count_component',
            new_name='has_first_count_component',
        ),
        migrations.RemoveField(
            model_name='workouttype',
            name='count_component2',
        ),
        migrations.AddField(
            model_name='workouttype',
            name='first_count_component',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workout_app.workouttypecount'),
        ),
        migrations.AddField(
            model_name='workouttype',
            name='has_second_count_component',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workouttype',
            name='second_count_component',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='second_cc', to='workout_app.workouttypecount'),
        ),
    ]
