# Generated by Django 3.1.7 on 2021-03-24 03:29

from django.db import migrations
import django_measurement.models
import measurement.measures.mass


class Migration(migrations.Migration):

    dependencies = [
        ('workout_app', '0025_auto_20210323_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutlinked',
            name='weight',
            field=django_measurement.models.MeasurementField(blank=True, default=0, measurement=measurement.measures.mass.Mass, null=True),
        ),
    ]
