# Generated by Django 3.1.7 on 2021-03-24 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout_app', '0026_auto_20210323_2329'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutlinked',
            name='one_day',
            field=models.BooleanField(default=True),
        ),
    ]
