# Generated by Django 3.1.7 on 2021-04-04 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout_app', '0028_delete_workout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutlinked',
            name='raw_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='workoutlinked',
            name='raw_rep',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='workoutlinked',
            name='raw_set',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='workoutlinked',
            name='second_raw_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
