# Generated by Django 3.1.7 on 2021-04-05 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout_app', '0031_auto_20210405_0131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutlinked',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
