# Generated by Django 3.1.7 on 2021-04-05 08:08

from django.db import migrations
import django_measurement.models
import measurement.measures.distance


class Migration(migrations.Migration):

    dependencies = [
        ('workout_app', '0033_auto_20210405_0406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutlinked',
            name='dist',
            field=django_measurement.models.MeasurementField(blank=True, default=0, measurement=measurement.measures.distance.Distance, null=True),
        ),
    ]
