# Generated by Django 3.1.7 on 2021-04-08 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout_app', '0039_achievement_second_specific_workouttypecount'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='second_specific_WorkoutTypeCount_min',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
