# Generated by Django 3.1.7 on 2021-04-08 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout_app', '0040_achievement_second_specific_workouttypecount_min'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='has_workout_count_min',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='achievement',
            name='workout_count_min',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
