# Generated by Django 3.1.7 on 2021-04-08 07:38

from django.db import migrations, models
import django_measurement.models
import measurement.measures.distance
import measurement.measures.mass


class Migration(migrations.Migration):

    dependencies = [
        ('workout_app', '0042_auto_20210408_0120'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='has_min_reps',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='achievement',
            name='has_min_single_distance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='achievement',
            name='has_min_single_duration',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='achievement',
            name='has_min_single_weight',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='achievement',
            name='has_min_total_distance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='achievement',
            name='has_min_total_duration',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='achievement',
            name='has_min_total_weight',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='achievement',
            name='min_reps',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='achievement',
            name='min_single_distance',
            field=django_measurement.models.MeasurementField(blank=True, default=0, measurement=measurement.measures.distance.Distance, null=True),
        ),
        migrations.AddField(
            model_name='achievement',
            name='min_single_duration',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='achievement',
            name='min_single_weight',
            field=django_measurement.models.MeasurementField(blank=True, default=0, measurement=measurement.measures.mass.Mass, null=True),
        ),
        migrations.AddField(
            model_name='achievement',
            name='min_total_distance',
            field=django_measurement.models.MeasurementField(blank=True, default=0, measurement=measurement.measures.distance.Distance, null=True),
        ),
        migrations.AddField(
            model_name='achievement',
            name='min_total_duration',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='achievement',
            name='min_total_weight',
            field=django_measurement.models.MeasurementField(blank=True, default=0, measurement=measurement.measures.mass.Mass, null=True),
        ),
        migrations.AddField(
            model_name='achievement',
            name='points',
            field=models.PositiveIntegerField(blank=True, default=10, null=True),
        ),
    ]
