# Generated by Django 3.1.7 on 2021-04-08 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout_app', '0043_auto_20210408_0338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutlinked',
            name='raw_rep',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='workoutlinked',
            name='raw_set',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
