# Generated by Django 3.1.7 on 2021-04-08 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout_app', '0045_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='achievement_num',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
