# Generated by Django 3.1.7 on 2021-04-11 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout_app', '0046_profile_achievement_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='has_max_pace',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='achievement',
            name='pace_per_mile',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
