# Generated by Django 3.1.6 on 2021-04-11 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout_app', '0048_auto_20210410_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profilePic',
            field=models.ImageField(default='defaultProfilePic.jpg', upload_to='userProfilePics'),
        ),
    ]
