# Generated by Django 3.1.6 on 2021-04-18 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workout_app', '0050_auto_20210411_1959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profilePic',
        ),
    ]
