# Generated by Django 3.1.7 on 2021-04-18 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout_app', '0052_profile_zipcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutlinked',
            name='zipcode',
            field=models.CharField(default='22904', max_length=5),
        ),
    ]
