# Generated by Django 3.1.7 on 2021-04-19 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workout_app', '0053_workoutlinked_zipcode'),
        ('workout_app', '0051_remove_profile_profilepic'),
    ]

    operations = [
    ]
