# Generated by Django 3.1.7 on 2021-04-21 00:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout_app', '0054_merge_20210418_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutlinked',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
