# Generated by Django 3.1.7 on 2021-04-21 00:48

from django.db import migrations
import django_measurement.models
import measurement.measures.distance


class Migration(migrations.Migration):

    dependencies = [
        ('workout_app', '0055_auto_20210420_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutlinked',
            name='dist',
            field=django_measurement.models.MeasurementField(default=0, measurement=measurement.measures.distance.Distance),
        ),
    ]
