# Generated by Django 3.1.7 on 2021-04-21 00:54

from django.db import migrations
import django_measurement.models
import measurement.measures.distance
import measurement.measures.mass


class Migration(migrations.Migration):

    dependencies = [
        ('workout_app', '0058_auto_20210420_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutlinked',
            name='dist',
            field=django_measurement.models.MeasurementField(default=0, measurement=measurement.measures.distance.Distance),
        ),
        migrations.AlterField(
            model_name='workoutlinked',
            name='weight',
            field=django_measurement.models.MeasurementField(default=0, measurement=measurement.measures.mass.Mass),
        ),
    ]
