# Generated by Django 3.1.7 on 2021-04-21 01:00

from django.db import migrations
import django_measurement.models
import measurement.measures.distance


class Migration(migrations.Migration):

    dependencies = [
        ('workout_app', '0059_auto_20210420_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutlinked',
            name='dist',
            field=django_measurement.models.MeasurementField(blank=True, measurement=measurement.measures.distance.Distance),
        ),
    ]
