# Generated by Django 3.1.7 on 2021-04-21 01:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout_app', '0061_auto_20210420_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutlinked',
            name='duration',
            field=models.DurationField(blank=True, default=datetime.timedelta(0)),
        ),
    ]
