# Generated by Django 3.1.7 on 2021-04-21 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout_app', '0062_auto_20210420_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutlinked',
            name='duration',
            field=models.DurationField(blank=True),
        ),
    ]
