# Generated by Django 3.1.7 on 2021-05-02 23:36

from django.db import migrations, models
import workout_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('workout_app', '0065_auto_20210422_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='zipcode',
            field=models.CharField(default='22904', max_length=5, validators=[workout_app.models.validate_zip]),
        ),
    ]
