# Generated by Django 3.1.7 on 2021-05-02 23:59

import datetime
from django.db import migrations, models
import workout_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('workout_app', '0066_auto_20210502_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutlinked',
            name='start_date',
            field=models.DateField(default=datetime.date.today, validators=[workout_app.models.validate_date_not_future]),
        ),
    ]
