# Generated by Django 3.1.7 on 2021-05-03 00:12

from django.db import migrations, models
import django_measurement.models
import measurement.measures.mass
import workout_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('workout_app', '0068_auto_20210502_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutlinked',
            name='weight',
            field=django_measurement.models.MeasurementField(blank=True, measurement=measurement.measures.mass.Mass, validators=[workout_app.models.validate_positive_weight]),
        ),
        migrations.AlterField(
            model_name='workoutlinked',
            name='zipcode',
            field=models.CharField(default='22904', max_length=5, validators=[workout_app.models.validate_zip]),
        ),
    ]
