# Generated by Django 3.1.7 on 2021-05-03 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout_app', '0070_auto_20210502_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutlinked',
            name='raw_rep',
            field=models.PositiveIntegerField(default=1, verbose_name='Reps'),
        ),
        migrations.AlterField(
            model_name='workoutlinked',
            name='raw_set',
            field=models.PositiveIntegerField(default=1, verbose_name='Sets'),
        ),
    ]
