# Generated by Django 3.1.7 on 2021-05-05 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout_app', '0073_auto_20210504_0006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workouttype',
            name='has_distance_comp',
            field=models.BooleanField(default=False, verbose_name='has distance component'),
        ),
        migrations.AlterField(
            model_name='workouttype',
            name='has_set_rep_comp',
            field=models.BooleanField(default=False, verbose_name='has set/rep component'),
        ),
        migrations.AlterField(
            model_name='workouttype',
            name='has_weight_comp',
            field=models.BooleanField(default=False, verbose_name='has weight component'),
        ),
    ]
