# Generated by Django 3.1.7 on 2021-05-05 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workout_app', '0074_auto_20210505_0356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workouttype',
            name='first_count_component',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workout_app.workouttypecount', verbose_name='first count component (if applicable)'),
        ),
        migrations.AlterField(
            model_name='workouttype',
            name='second_count_component',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='second_cc', to='workout_app.workouttypecount', verbose_name='second count component (if applicable)'),
        ),
    ]
