# Generated by Django 3.1.7 on 2021-05-05 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout_app', '0075_auto_20210505_0357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workouttype',
            name='type_name',
            field=models.CharField(default='', max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='workouttypecount',
            name='type_name',
            field=models.CharField(default='', max_length=30, unique=True),
        ),
    ]
